[package]
name = "ruminative"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracy-client = "0.16.*"
imgui = { version = "0.11.*", features = ["docking"] }
imgui-sys = { version = "0.11.0", features = ["docking"] }
vulkano = "0.34.*"
vulkano-win = "0.34.*"
vulkano-shaders = "0.34.*"
smallvec = "1.11.*"
winit = "0.28.*"
png = "0.17.*"
texpresso = "2.0.*"

[profile.release]
strip = true

[profile.dev]
#strip = true
opt-level = 1
overflow-checks = false
incremental = true

[profile.dev.package."*"]
#strip = true
opt-level = 3
overflow-checks = false
incremental = true
